// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/proto/plugin/v1/plugin.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginLifecycle_Handshake_FullMethodName      = "/weknora.plugin.v1.PluginLifecycle/Handshake"
	PluginLifecycle_HealthCheck_FullMethodName    = "/weknora.plugin.v1.PluginLifecycle/HealthCheck"
	PluginLifecycle_ValidateConfig_FullMethodName = "/weknora.plugin.v1.PluginLifecycle/ValidateConfig"
)

// PluginLifecycleClient is the client API for PluginLifecycle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginLifecycle is implemented by every plugin. The runtime also exposes
// this service as a proxy and selects the target from context.plugin_id.
type PluginLifecycleClient interface {
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error)
}

type pluginLifecycleClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginLifecycleClient(cc grpc.ClientConnInterface) PluginLifecycleClient {
	return &pluginLifecycleClient{cc}
}

func (c *pluginLifecycleClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, PluginLifecycle_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginLifecycleClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, PluginLifecycle_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginLifecycleClient) ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateConfigResponse)
	err := c.cc.Invoke(ctx, PluginLifecycle_ValidateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginLifecycleServer is the server API for PluginLifecycle service.
// All implementations must embed UnimplementedPluginLifecycleServer
// for forward compatibility.
//
// PluginLifecycle is implemented by every plugin. The runtime also exposes
// this service as a proxy and selects the target from context.plugin_id.
type PluginLifecycleServer interface {
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error)
	mustEmbedUnimplementedPluginLifecycleServer()
}

// UnimplementedPluginLifecycleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginLifecycleServer struct{}

func (UnimplementedPluginLifecycleServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedPluginLifecycleServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPluginLifecycleServer) ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateConfig not implemented")
}
func (UnimplementedPluginLifecycleServer) mustEmbedUnimplementedPluginLifecycleServer() {}
func (UnimplementedPluginLifecycleServer) testEmbeddedByValue()                         {}

// UnsafePluginLifecycleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginLifecycleServer will
// result in compilation errors.
type UnsafePluginLifecycleServer interface {
	mustEmbedUnimplementedPluginLifecycleServer()
}

func RegisterPluginLifecycleServer(s grpc.ServiceRegistrar, srv PluginLifecycleServer) {
	// If the following call panics, it indicates UnimplementedPluginLifecycleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginLifecycle_ServiceDesc, srv)
}

func _PluginLifecycle_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginLifecycleServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginLifecycle_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginLifecycleServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginLifecycle_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginLifecycleServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginLifecycle_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginLifecycleServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginLifecycle_ValidateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginLifecycleServer).ValidateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginLifecycle_ValidateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginLifecycleServer).ValidateConfig(ctx, req.(*ValidateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginLifecycle_ServiceDesc is the grpc.ServiceDesc for PluginLifecycle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginLifecycle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weknora.plugin.v1.PluginLifecycle",
	HandlerType: (*PluginLifecycleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _PluginLifecycle_Handshake_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PluginLifecycle_HealthCheck_Handler,
		},
		{
			MethodName: "ValidateConfig",
			Handler:    _PluginLifecycle_ValidateConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/plugin/v1/plugin.proto",
}

const (
	DataSourcePlugin_ListResources_FullMethodName            = "/weknora.plugin.v1.DataSourcePlugin/ListResources"
	DataSourcePlugin_ResolveResourceAncestors_FullMethodName = "/weknora.plugin.v1.DataSourcePlugin/ResolveResourceAncestors"
	DataSourcePlugin_Sync_FullMethodName                     = "/weknora.plugin.v1.DataSourcePlugin/Sync"
)

// DataSourcePluginClient is the client API for DataSourcePlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataSourcePlugin converts source-specific objects into a common document
// event stream. A document is transferred as begin -> chunk* -> end so large
// files never depend on the gRPC unary message limit.
type DataSourcePluginClient interface {
	ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error)
	ResolveResourceAncestors(ctx context.Context, in *ResolveResourceAncestorsRequest, opts ...grpc.CallOption) (*ResolveResourceAncestorsResponse, error)
	Sync(ctx context.Context, in *DataSourceSyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataSourceSyncEvent], error)
}

type dataSourcePluginClient struct {
	cc grpc.ClientConnInterface
}

func NewDataSourcePluginClient(cc grpc.ClientConnInterface) DataSourcePluginClient {
	return &dataSourcePluginClient{cc}
}

func (c *dataSourcePluginClient) ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourcesResponse)
	err := c.cc.Invoke(ctx, DataSourcePlugin_ListResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourcePluginClient) ResolveResourceAncestors(ctx context.Context, in *ResolveResourceAncestorsRequest, opts ...grpc.CallOption) (*ResolveResourceAncestorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveResourceAncestorsResponse)
	err := c.cc.Invoke(ctx, DataSourcePlugin_ResolveResourceAncestors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourcePluginClient) Sync(ctx context.Context, in *DataSourceSyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataSourceSyncEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataSourcePlugin_ServiceDesc.Streams[0], DataSourcePlugin_Sync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataSourceSyncRequest, DataSourceSyncEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataSourcePlugin_SyncClient = grpc.ServerStreamingClient[DataSourceSyncEvent]

// DataSourcePluginServer is the server API for DataSourcePlugin service.
// All implementations must embed UnimplementedDataSourcePluginServer
// for forward compatibility.
//
// DataSourcePlugin converts source-specific objects into a common document
// event stream. A document is transferred as begin -> chunk* -> end so large
// files never depend on the gRPC unary message limit.
type DataSourcePluginServer interface {
	ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error)
	ResolveResourceAncestors(context.Context, *ResolveResourceAncestorsRequest) (*ResolveResourceAncestorsResponse, error)
	Sync(*DataSourceSyncRequest, grpc.ServerStreamingServer[DataSourceSyncEvent]) error
	mustEmbedUnimplementedDataSourcePluginServer()
}

// UnimplementedDataSourcePluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataSourcePluginServer struct{}

func (UnimplementedDataSourcePluginServer) ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListResources not implemented")
}
func (UnimplementedDataSourcePluginServer) ResolveResourceAncestors(context.Context, *ResolveResourceAncestorsRequest) (*ResolveResourceAncestorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveResourceAncestors not implemented")
}
func (UnimplementedDataSourcePluginServer) Sync(*DataSourceSyncRequest, grpc.ServerStreamingServer[DataSourceSyncEvent]) error {
	return status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedDataSourcePluginServer) mustEmbedUnimplementedDataSourcePluginServer() {}
func (UnimplementedDataSourcePluginServer) testEmbeddedByValue()                          {}

// UnsafeDataSourcePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataSourcePluginServer will
// result in compilation errors.
type UnsafeDataSourcePluginServer interface {
	mustEmbedUnimplementedDataSourcePluginServer()
}

func RegisterDataSourcePluginServer(s grpc.ServiceRegistrar, srv DataSourcePluginServer) {
	// If the following call panics, it indicates UnimplementedDataSourcePluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataSourcePlugin_ServiceDesc, srv)
}

func _DataSourcePlugin_ListResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourcePluginServer).ListResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourcePlugin_ListResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourcePluginServer).ListResources(ctx, req.(*ListResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourcePlugin_ResolveResourceAncestors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveResourceAncestorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourcePluginServer).ResolveResourceAncestors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourcePlugin_ResolveResourceAncestors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourcePluginServer).ResolveResourceAncestors(ctx, req.(*ResolveResourceAncestorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourcePlugin_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DataSourceSyncRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataSourcePluginServer).Sync(m, &grpc.GenericServerStream[DataSourceSyncRequest, DataSourceSyncEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataSourcePlugin_SyncServer = grpc.ServerStreamingServer[DataSourceSyncEvent]

// DataSourcePlugin_ServiceDesc is the grpc.ServiceDesc for DataSourcePlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataSourcePlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weknora.plugin.v1.DataSourcePlugin",
	HandlerType: (*DataSourcePluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListResources",
			Handler:    _DataSourcePlugin_ListResources_Handler,
		},
		{
			MethodName: "ResolveResourceAncestors",
			Handler:    _DataSourcePlugin_ResolveResourceAncestors_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _DataSourcePlugin_Sync_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/plugin/v1/plugin.proto",
}

const (
	DocumentParserPlugin_Parse_FullMethodName = "/weknora.plugin.v1.DocumentParserPlugin/Parse"
)

// DocumentParserPluginClient is the client API for DocumentParserPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DocumentParserPlugin is the extension point for out-of-process parsers.
// The first request frame must be ParseBegin, followed by zero or more chunks.
type DocumentParserPluginClient interface {
	Parse(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ParseRequest, ParseEvent], error)
}

type documentParserPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentParserPluginClient(cc grpc.ClientConnInterface) DocumentParserPluginClient {
	return &documentParserPluginClient{cc}
}

func (c *documentParserPluginClient) Parse(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ParseRequest, ParseEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DocumentParserPlugin_ServiceDesc.Streams[0], DocumentParserPlugin_Parse_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ParseRequest, ParseEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentParserPlugin_ParseClient = grpc.BidiStreamingClient[ParseRequest, ParseEvent]

// DocumentParserPluginServer is the server API for DocumentParserPlugin service.
// All implementations must embed UnimplementedDocumentParserPluginServer
// for forward compatibility.
//
// DocumentParserPlugin is the extension point for out-of-process parsers.
// The first request frame must be ParseBegin, followed by zero or more chunks.
type DocumentParserPluginServer interface {
	Parse(grpc.BidiStreamingServer[ParseRequest, ParseEvent]) error
	mustEmbedUnimplementedDocumentParserPluginServer()
}

// UnimplementedDocumentParserPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentParserPluginServer struct{}

func (UnimplementedDocumentParserPluginServer) Parse(grpc.BidiStreamingServer[ParseRequest, ParseEvent]) error {
	return status.Error(codes.Unimplemented, "method Parse not implemented")
}
func (UnimplementedDocumentParserPluginServer) mustEmbedUnimplementedDocumentParserPluginServer() {}
func (UnimplementedDocumentParserPluginServer) testEmbeddedByValue()                              {}

// UnsafeDocumentParserPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentParserPluginServer will
// result in compilation errors.
type UnsafeDocumentParserPluginServer interface {
	mustEmbedUnimplementedDocumentParserPluginServer()
}

func RegisterDocumentParserPluginServer(s grpc.ServiceRegistrar, srv DocumentParserPluginServer) {
	// If the following call panics, it indicates UnimplementedDocumentParserPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentParserPlugin_ServiceDesc, srv)
}

func _DocumentParserPlugin_Parse_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DocumentParserPluginServer).Parse(&grpc.GenericServerStream[ParseRequest, ParseEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentParserPlugin_ParseServer = grpc.BidiStreamingServer[ParseRequest, ParseEvent]

// DocumentParserPlugin_ServiceDesc is the grpc.ServiceDesc for DocumentParserPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentParserPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weknora.plugin.v1.DocumentParserPlugin",
	HandlerType: (*DocumentParserPluginServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Parse",
			Handler:       _DocumentParserPlugin_Parse_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/plugin/v1/plugin.proto",
}

const (
	WebSearchPlugin_Search_FullMethodName = "/weknora.plugin.v1.WebSearchPlugin/Search"
)

// WebSearchPluginClient is the client API for WebSearchPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WebSearchPlugin is the extension point for external search engines.
type WebSearchPluginClient interface {
	Search(ctx context.Context, in *WebSearchRequest, opts ...grpc.CallOption) (*WebSearchResponse, error)
}

type webSearchPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewWebSearchPluginClient(cc grpc.ClientConnInterface) WebSearchPluginClient {
	return &webSearchPluginClient{cc}
}

func (c *webSearchPluginClient) Search(ctx context.Context, in *WebSearchRequest, opts ...grpc.CallOption) (*WebSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebSearchResponse)
	err := c.cc.Invoke(ctx, WebSearchPlugin_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebSearchPluginServer is the server API for WebSearchPlugin service.
// All implementations must embed UnimplementedWebSearchPluginServer
// for forward compatibility.
//
// WebSearchPlugin is the extension point for external search engines.
type WebSearchPluginServer interface {
	Search(context.Context, *WebSearchRequest) (*WebSearchResponse, error)
	mustEmbedUnimplementedWebSearchPluginServer()
}

// UnimplementedWebSearchPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebSearchPluginServer struct{}

func (UnimplementedWebSearchPluginServer) Search(context.Context, *WebSearchRequest) (*WebSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedWebSearchPluginServer) mustEmbedUnimplementedWebSearchPluginServer() {}
func (UnimplementedWebSearchPluginServer) testEmbeddedByValue()                         {}

// UnsafeWebSearchPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebSearchPluginServer will
// result in compilation errors.
type UnsafeWebSearchPluginServer interface {
	mustEmbedUnimplementedWebSearchPluginServer()
}

func RegisterWebSearchPluginServer(s grpc.ServiceRegistrar, srv WebSearchPluginServer) {
	// If the following call panics, it indicates UnimplementedWebSearchPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebSearchPlugin_ServiceDesc, srv)
}

func _WebSearchPlugin_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebSearchPluginServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebSearchPlugin_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebSearchPluginServer).Search(ctx, req.(*WebSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebSearchPlugin_ServiceDesc is the grpc.ServiceDesc for WebSearchPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebSearchPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weknora.plugin.v1.WebSearchPlugin",
	HandlerType: (*WebSearchPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _WebSearchPlugin_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/plugin/v1/plugin.proto",
}

const (
	ModelProviderPlugin_ListModels_FullMethodName = "/weknora.plugin.v1.ModelProviderPlugin/ListModels"
	ModelProviderPlugin_Chat_FullMethodName       = "/weknora.plugin.v1.ModelProviderPlugin/Chat"
	ModelProviderPlugin_Embed_FullMethodName      = "/weknora.plugin.v1.ModelProviderPlugin/Embed"
	ModelProviderPlugin_Rerank_FullMethodName     = "/weknora.plugin.v1.ModelProviderPlugin/Rerank"
)

// ModelProviderPluginClient is the client API for ModelProviderPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ModelProviderPlugin keeps each model capability explicit. A provider only
// advertises and implements capabilities listed in its manifest.
type ModelProviderPluginClient interface {
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error)
	Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error)
	Rerank(ctx context.Context, in *RerankRequest, opts ...grpc.CallOption) (*RerankResponse, error)
}

type modelProviderPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewModelProviderPluginClient(cc grpc.ClientConnInterface) ModelProviderPluginClient {
	return &modelProviderPluginClient{cc}
}

func (c *modelProviderPluginClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, ModelProviderPlugin_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelProviderPluginClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ModelProviderPlugin_ServiceDesc.Streams[0], ModelProviderPlugin_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelProviderPlugin_ChatClient = grpc.ServerStreamingClient[ChatEvent]

func (c *modelProviderPluginClient) Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedResponse)
	err := c.cc.Invoke(ctx, ModelProviderPlugin_Embed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelProviderPluginClient) Rerank(ctx context.Context, in *RerankRequest, opts ...grpc.CallOption) (*RerankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RerankResponse)
	err := c.cc.Invoke(ctx, ModelProviderPlugin_Rerank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelProviderPluginServer is the server API for ModelProviderPlugin service.
// All implementations must embed UnimplementedModelProviderPluginServer
// for forward compatibility.
//
// ModelProviderPlugin keeps each model capability explicit. A provider only
// advertises and implements capabilities listed in its manifest.
type ModelProviderPluginServer interface {
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	Chat(*ChatRequest, grpc.ServerStreamingServer[ChatEvent]) error
	Embed(context.Context, *EmbedRequest) (*EmbedResponse, error)
	Rerank(context.Context, *RerankRequest) (*RerankResponse, error)
	mustEmbedUnimplementedModelProviderPluginServer()
}

// UnimplementedModelProviderPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelProviderPluginServer struct{}

func (UnimplementedModelProviderPluginServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedModelProviderPluginServer) Chat(*ChatRequest, grpc.ServerStreamingServer[ChatEvent]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedModelProviderPluginServer) Embed(context.Context, *EmbedRequest) (*EmbedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Embed not implemented")
}
func (UnimplementedModelProviderPluginServer) Rerank(context.Context, *RerankRequest) (*RerankResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rerank not implemented")
}
func (UnimplementedModelProviderPluginServer) mustEmbedUnimplementedModelProviderPluginServer() {}
func (UnimplementedModelProviderPluginServer) testEmbeddedByValue()                             {}

// UnsafeModelProviderPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelProviderPluginServer will
// result in compilation errors.
type UnsafeModelProviderPluginServer interface {
	mustEmbedUnimplementedModelProviderPluginServer()
}

func RegisterModelProviderPluginServer(s grpc.ServiceRegistrar, srv ModelProviderPluginServer) {
	// If the following call panics, it indicates UnimplementedModelProviderPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelProviderPlugin_ServiceDesc, srv)
}

func _ModelProviderPlugin_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelProviderPluginServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelProviderPlugin_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelProviderPluginServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelProviderPlugin_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModelProviderPluginServer).Chat(m, &grpc.GenericServerStream[ChatRequest, ChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelProviderPlugin_ChatServer = grpc.ServerStreamingServer[ChatEvent]

func _ModelProviderPlugin_Embed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelProviderPluginServer).Embed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelProviderPlugin_Embed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelProviderPluginServer).Embed(ctx, req.(*EmbedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelProviderPlugin_Rerank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RerankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelProviderPluginServer).Rerank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelProviderPlugin_Rerank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelProviderPluginServer).Rerank(ctx, req.(*RerankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelProviderPlugin_ServiceDesc is the grpc.ServiceDesc for ModelProviderPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelProviderPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weknora.plugin.v1.ModelProviderPlugin",
	HandlerType: (*ModelProviderPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListModels",
			Handler:    _ModelProviderPlugin_ListModels_Handler,
		},
		{
			MethodName: "Embed",
			Handler:    _ModelProviderPlugin_Embed_Handler,
		},
		{
			MethodName: "Rerank",
			Handler:    _ModelProviderPlugin_Rerank_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _ModelProviderPlugin_Chat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/plugin/v1/plugin.proto",
}

const (
	PluginRuntime_Install_FullMethodName      = "/weknora.plugin.v1.PluginRuntime/Install"
	PluginRuntime_Upgrade_FullMethodName      = "/weknora.plugin.v1.PluginRuntime/Upgrade"
	PluginRuntime_Start_FullMethodName        = "/weknora.plugin.v1.PluginRuntime/Start"
	PluginRuntime_Stop_FullMethodName         = "/weknora.plugin.v1.PluginRuntime/Stop"
	PluginRuntime_Uninstall_FullMethodName    = "/weknora.plugin.v1.PluginRuntime/Uninstall"
	PluginRuntime_GetStatus_FullMethodName    = "/weknora.plugin.v1.PluginRuntime/GetStatus"
	PluginRuntime_ListStatuses_FullMethodName = "/weknora.plugin.v1.PluginRuntime/ListStatuses"
	PluginRuntime_WatchEvents_FullMethodName  = "/weknora.plugin.v1.PluginRuntime/WatchEvents"
)

// PluginRuntimeClient is the client API for PluginRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginRuntime owns container lifecycle. WeKnora talks to this service and
// never mounts or calls the Docker socket itself.
type PluginRuntimeClient interface {
	Install(ctx context.Context, in *InstallPluginRequest, opts ...grpc.CallOption) (*PluginRuntimeStatus, error)
	Upgrade(ctx context.Context, in *UpgradePluginRequest, opts ...grpc.CallOption) (*PluginRuntimeStatus, error)
	Start(ctx context.Context, in *PluginTargetRequest, opts ...grpc.CallOption) (*PluginRuntimeStatus, error)
	Stop(ctx context.Context, in *PluginTargetRequest, opts ...grpc.CallOption) (*PluginRuntimeStatus, error)
	Uninstall(ctx context.Context, in *PluginTargetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetStatus(ctx context.Context, in *PluginTargetRequest, opts ...grpc.CallOption) (*PluginRuntimeStatus, error)
	ListStatuses(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListPluginStatusesResponse, error)
	WatchEvents(ctx context.Context, in *WatchRuntimeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RuntimeEvent], error)
}

type pluginRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginRuntimeClient(cc grpc.ClientConnInterface) PluginRuntimeClient {
	return &pluginRuntimeClient{cc}
}

func (c *pluginRuntimeClient) Install(ctx context.Context, in *InstallPluginRequest, opts ...grpc.CallOption) (*PluginRuntimeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginRuntimeStatus)
	err := c.cc.Invoke(ctx, PluginRuntime_Install_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginRuntimeClient) Upgrade(ctx context.Context, in *UpgradePluginRequest, opts ...grpc.CallOption) (*PluginRuntimeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginRuntimeStatus)
	err := c.cc.Invoke(ctx, PluginRuntime_Upgrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginRuntimeClient) Start(ctx context.Context, in *PluginTargetRequest, opts ...grpc.CallOption) (*PluginRuntimeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginRuntimeStatus)
	err := c.cc.Invoke(ctx, PluginRuntime_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginRuntimeClient) Stop(ctx context.Context, in *PluginTargetRequest, opts ...grpc.CallOption) (*PluginRuntimeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginRuntimeStatus)
	err := c.cc.Invoke(ctx, PluginRuntime_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginRuntimeClient) Uninstall(ctx context.Context, in *PluginTargetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PluginRuntime_Uninstall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginRuntimeClient) GetStatus(ctx context.Context, in *PluginTargetRequest, opts ...grpc.CallOption) (*PluginRuntimeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginRuntimeStatus)
	err := c.cc.Invoke(ctx, PluginRuntime_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginRuntimeClient) ListStatuses(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListPluginStatusesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPluginStatusesResponse)
	err := c.cc.Invoke(ctx, PluginRuntime_ListStatuses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginRuntimeClient) WatchEvents(ctx context.Context, in *WatchRuntimeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RuntimeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PluginRuntime_ServiceDesc.Streams[0], PluginRuntime_WatchEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRuntimeEventsRequest, RuntimeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginRuntime_WatchEventsClient = grpc.ServerStreamingClient[RuntimeEvent]

// PluginRuntimeServer is the server API for PluginRuntime service.
// All implementations must embed UnimplementedPluginRuntimeServer
// for forward compatibility.
//
// PluginRuntime owns container lifecycle. WeKnora talks to this service and
// never mounts or calls the Docker socket itself.
type PluginRuntimeServer interface {
	Install(context.Context, *InstallPluginRequest) (*PluginRuntimeStatus, error)
	Upgrade(context.Context, *UpgradePluginRequest) (*PluginRuntimeStatus, error)
	Start(context.Context, *PluginTargetRequest) (*PluginRuntimeStatus, error)
	Stop(context.Context, *PluginTargetRequest) (*PluginRuntimeStatus, error)
	Uninstall(context.Context, *PluginTargetRequest) (*emptypb.Empty, error)
	GetStatus(context.Context, *PluginTargetRequest) (*PluginRuntimeStatus, error)
	ListStatuses(context.Context, *emptypb.Empty) (*ListPluginStatusesResponse, error)
	WatchEvents(*WatchRuntimeEventsRequest, grpc.ServerStreamingServer[RuntimeEvent]) error
	mustEmbedUnimplementedPluginRuntimeServer()
}

// UnimplementedPluginRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginRuntimeServer struct{}

func (UnimplementedPluginRuntimeServer) Install(context.Context, *InstallPluginRequest) (*PluginRuntimeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Install not implemented")
}
func (UnimplementedPluginRuntimeServer) Upgrade(context.Context, *UpgradePluginRequest) (*PluginRuntimeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Upgrade not implemented")
}
func (UnimplementedPluginRuntimeServer) Start(context.Context, *PluginTargetRequest) (*PluginRuntimeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedPluginRuntimeServer) Stop(context.Context, *PluginTargetRequest) (*PluginRuntimeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedPluginRuntimeServer) Uninstall(context.Context, *PluginTargetRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Uninstall not implemented")
}
func (UnimplementedPluginRuntimeServer) GetStatus(context.Context, *PluginTargetRequest) (*PluginRuntimeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedPluginRuntimeServer) ListStatuses(context.Context, *emptypb.Empty) (*ListPluginStatusesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStatuses not implemented")
}
func (UnimplementedPluginRuntimeServer) WatchEvents(*WatchRuntimeEventsRequest, grpc.ServerStreamingServer[RuntimeEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchEvents not implemented")
}
func (UnimplementedPluginRuntimeServer) mustEmbedUnimplementedPluginRuntimeServer() {}
func (UnimplementedPluginRuntimeServer) testEmbeddedByValue()                       {}

// UnsafePluginRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginRuntimeServer will
// result in compilation errors.
type UnsafePluginRuntimeServer interface {
	mustEmbedUnimplementedPluginRuntimeServer()
}

func RegisterPluginRuntimeServer(s grpc.ServiceRegistrar, srv PluginRuntimeServer) {
	// If the following call panics, it indicates UnimplementedPluginRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginRuntime_ServiceDesc, srv)
}

func _PluginRuntime_Install_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRuntimeServer).Install(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginRuntime_Install_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRuntimeServer).Install(ctx, req.(*InstallPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginRuntime_Upgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRuntimeServer).Upgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginRuntime_Upgrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRuntimeServer).Upgrade(ctx, req.(*UpgradePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginRuntime_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRuntimeServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginRuntime_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRuntimeServer).Start(ctx, req.(*PluginTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginRuntime_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRuntimeServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginRuntime_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRuntimeServer).Stop(ctx, req.(*PluginTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginRuntime_Uninstall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRuntimeServer).Uninstall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginRuntime_Uninstall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRuntimeServer).Uninstall(ctx, req.(*PluginTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginRuntime_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRuntimeServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginRuntime_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRuntimeServer).GetStatus(ctx, req.(*PluginTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginRuntime_ListStatuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRuntimeServer).ListStatuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginRuntime_ListStatuses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRuntimeServer).ListStatuses(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginRuntime_WatchEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRuntimeEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PluginRuntimeServer).WatchEvents(m, &grpc.GenericServerStream[WatchRuntimeEventsRequest, RuntimeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginRuntime_WatchEventsServer = grpc.ServerStreamingServer[RuntimeEvent]

// PluginRuntime_ServiceDesc is the grpc.ServiceDesc for PluginRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weknora.plugin.v1.PluginRuntime",
	HandlerType: (*PluginRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Install",
			Handler:    _PluginRuntime_Install_Handler,
		},
		{
			MethodName: "Upgrade",
			Handler:    _PluginRuntime_Upgrade_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _PluginRuntime_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _PluginRuntime_Stop_Handler,
		},
		{
			MethodName: "Uninstall",
			Handler:    _PluginRuntime_Uninstall_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _PluginRuntime_GetStatus_Handler,
		},
		{
			MethodName: "ListStatuses",
			Handler:    _PluginRuntime_ListStatuses_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEvents",
			Handler:       _PluginRuntime_WatchEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/plugin/v1/plugin.proto",
}
